pandas(Created by Wes McKinney in 2008)
    pandas contain high-level datastructures and manipulation tools designed to make data analysis fast and easy.
    pandas are built on top of numpy which makes it easy to use in numpy centric applications.

In [5]:
import pandas as pd
import numpy as np

In [6]:
labels = ['a', 'b', 'c']
my_data = [1, 2, 3]
arr = np.array(my_data)

Syantax for creating a series
pd.Series(data, index)

In [9]:
my_series = pd.Series(my_data, labels)

In [17]:
my_series['c']

3

In [18]:
my_series+my_series

a    2
b    4
c    6
dtype: int64

In [21]:
from numpy.random import randn

In [22]:
np.random.seed(10)

In [24]:
df = pd.DataFrame(data=randn(5, 4), index=['A', 'B', 'C', 'D', 'E'], columns=['W', 'X', 'Y', 'Z'])

In [28]:
type(df['X'])

pandas.core.series.Series

In [29]:
df[['W', 'X']]

          W         X
A -1.977728 -1.743372
B  1.123691  1.672622
C -0.271248  0.613204
D  0.132708 -0.476142
E  0.400210 -0.337632

In [30]:
df['new'] = df['W'] + df['X']

In [33]:
df.drop('new', axis=1, inplace=True)

In [35]:
df.drop('E', axis=0, inplace=True)

In [36]:
df

          W         X         Y         Z
A -1.977728 -1.743372  0.266070  2.384967
B  1.123691  1.672622  0.099149  1.397996
C -0.271248  0.613204 -0.267317 -0.549309
D  0.132708 -0.476142  1.308473  0.195013

In [38]:
df.shape # Returns a tuple consisting of rows, columns

(4, 4)

In [39]:
df.loc['A']

W   -1.977728
X   -1.743372
Y    0.266070
Z    2.384967
Name: A, dtype: float64

In [40]:
df.iloc[1]

W    1.123691
X    1.672622
Y    0.099149
Z    1.397996
Name: B, dtype: float64

In [43]:
df.loc[['A', 'B'], ['Y', 'W']]

          Y         W
A  0.266070 -1.977728
B  0.099149  1.123691

In [44]:
df.axes

[Index(['A', 'B', 'C', 'D'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]