pandas(Created by Wes McKinney in 2008)
    pandas contain high-level datastructures and manipulation tools designed to make data analysis fast and easy.
    pandas are built on top of numpy which makes it easy to use in numpy centric applications.

In [2]:
import pandas as pd
import numpy as np

In [2]:
labels = ['a', 'b', 'c']
my_data = [1, 2, 3]
arr = np.array(my_data)

Syantax for creating a series
pd.Series(data, index)

In [3]:
my_series = pd.Series(my_data, labels) # Creating a series

In [4]:
my_series['c']

3

In [5]:
my_series+my_series

a    2
b    4
c    6
dtype: int64

In [6]:
from numpy.random import randn

In [7]:
np.random.seed(10)

In [8]:
df = pd.DataFrame(data=randn(5, 4), index=['A', 'B', 'C', 'D', 'E'], columns=['W', 'X', 'Y', 'Z'])

In [9]:
type(df['X'])

pandas.core.series.Series

In [10]:
df[['W', 'X']] # Slicing a dataframe

          W         X
A  1.331587  0.715279
B  0.621336 -0.720086
C  0.004291 -0.174600
D -0.965066  1.028274
E -1.136602  0.135137

In [11]:
df['new'] = df['W'] + df['X']

In [12]:
df.drop('new', axis=1, inplace=True)

In [13]:
df.drop('E', axis=0, inplace=True)

In [14]:
df

          W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138

In [15]:
df.shape # Returns a tuple consisting of rows, columns

(4, 4)

In [16]:
df.loc['A']

W    1.331587
X    0.715279
Y   -1.545400
Z   -0.008384
Name: A, dtype: float64

In [17]:
df.iloc[1]

W    0.621336
X   -0.720086
Y    0.265512
Z    0.108549
Name: B, dtype: float64

In [18]:
df.loc[['A', 'B'], ['Y', 'W']]

          Y         W
A -1.545400  1.331587
B  0.265512  0.621336

In [19]:
df.axes

[Index(['A', 'B', 'C', 'D'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [22]:
booldf = df > 0 # Conditional selection returns boolean values.

In [33]:
df[df['Z'] > 0][['X', 'W']]

          X         W
B -0.720086  0.621336
C -0.174600  0.004291
D  1.028274 -0.965066

In [ ]:
# set vs reset index

In [ ]:
#multi index and index hierarchy

In [17]:
# Missing values
d = {'A':[1, 2], 'B':[5, np.nan]}
df = pd.DataFrame(d)

In [18]:
df # Threshold value (min no of nan for the row or col to be dropped.)

   A    B
0  1  5.0
1  2  NaN

In [ ]:
# the fillna(value=) method, v Important

In [19]:
df.fillna(value=df['A'].mean())

   A    B
0  1  5.0
1  2  1.5